/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Color;
import java.util.Locale;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author lasin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private TimGV timGV;
    private DiemSV diemSV;
    private ThongKeDiem tkDiem;
    public Admin() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("/Image/user.png")).getImage();
        this.setIconImage(img);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_laplich = new Form.MyButton();
        btn_thongke = new Form.MyButton();
        btn_nhapdiemsv = new Form.MyButton();
        btn_logout = new Form.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setLocation(new java.awt.Point(800, 300));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        btn_laplich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/schedule.png"))); // NOI18N
        btn_laplich.setText("Lập lịch GV");
        btn_laplich.setBorderColor(new java.awt.Color(0, 51, 255));
        btn_laplich.setColorClick(new java.awt.Color(102, 102, 255));
        btn_laplich.setColorOver(new java.awt.Color(204, 204, 255));
        btn_laplich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_laplich.setRadius(50);
        btn_laplich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaovienActionPerformed(evt);
            }
        });

        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar-chart.png"))); // NOI18N
        btn_thongke.setText("Thống Kê");
        btn_thongke.setBorderColor(new java.awt.Color(0, 204, 204));
        btn_thongke.setColorClick(new java.awt.Color(51, 255, 204));
        btn_thongke.setColorOver(new java.awt.Color(153, 255, 204));
        btn_thongke.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_thongke.setRadius(50);
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkActionPerformed(evt);
            }
        });

        btn_nhapdiemsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert.png"))); // NOI18N
        btn_nhapdiemsv.setText("Nhập điểm SV");
        btn_nhapdiemsv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_nhapdiemsv.setRadius(50);
        btn_nhapdiemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sinhvienActionPerformed(evt);
            }
        });

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancels.png"))); // NOI18N
        btn_logout.setText("Đăng Xuất");
        btn_logout.setBorderColor(new java.awt.Color(255, 0, 0));
        btn_logout.setColorClick(new java.awt.Color(255, 102, 102));
        btn_logout.setColorOver(new java.awt.Color(255, 204, 204));
        btn_logout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_logout.setRadius(50);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_laplich, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_laplich, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sinhvienActionPerformed
        diemSV=new DiemSV("admin");
        diemSV.setLocation(400,200);
        diemSV.setVisible(true);
    }//GEN-LAST:event_btn_sinhvienActionPerformed

    private void btn_giaovienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaovienActionPerformed
        timGV=new TimGV(this);
        timGV.setLocation(400,200);
        timGV.setVisible(true);
    }//GEN-LAST:event_btn_giaovienActionPerformed

    private void btn_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkActionPerformed
        tkDiem=new ThongKeDiem(this);
        tkDiem.setLocation(400,200);
        tkDiem.setVisible(true);
    }//GEN-LAST:event_btn_tkActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        FormDangNhapAdmin formDangNhapAdmin=new FormDangNhapAdmin();
        formDangNhapAdmin.setVisible(true);
        this.setVisible(false);
        formDangNhapAdmin.setLocation(400,400);
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Form.MyButton btn_laplich;
    private Form.MyButton btn_logout;
    private Form.MyButton btn_nhapdiemsv;
    private Form.MyButton btn_thongke;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
