/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;


import javax.swing.JFrame;
import Domain.Lop;
import Domain.SinhVien;
import Domain.LopHocPhan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Repository.JdbcLopHocPhan;
import Repository.JdbcSinhVien;
import Repository.JdbcLop;
import Repository.SinhVien_Helper;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author lasin
 */
public class DiemSV extends javax.swing.JFrame {

    private Admin admin;
    String tinhieu;
    JdbcSinhVien listsv;
    JdbcLopHocPhan listlhp;
    List<SinhVien> list;
    List<LopHocPhan>listhp;
    int dem1=0,dem2=0;
    /**
    
     * Creates new form DiemSV
     */
    public DiemSV(String check) {
        tinhieu=check;
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("/Image/exam.png")).getImage();
        this.setIconImage(img);
        if(!tinhieu.equals("admin")){
            btn_xemtkb.setEnabled(false);
            btn_xemtkb.setVisible(false);
        }
        //this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_lop = new javax.swing.JRadioButton();
        rb_mssv = new javax.swing.JRadioButton();
        txt_ma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_xemtkb = new Form.MyButton();
        btn_nhapdiemsv = new Form.MyButton();
        jPanel2 = new javax.swing.JPanel();
        cb_hocki = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cb_nam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin điểm");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm thông tin sinh viên  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        buttonGroup1.add(rb_lop);
        rb_lop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb_lop.setForeground(new java.awt.Color(0, 0, 255));
        rb_lop.setText("Tim theo lop");
        rb_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_lopActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_mssv);
        rb_mssv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb_mssv.setForeground(new java.awt.Color(0, 0, 255));
        rb_mssv.setText("Tim theo MSSV");
        rb_mssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mssvActionPerformed(evt);
            }
        });

        txt_ma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "MSSV", "MaLopHP", "Tên Sinh viên"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(6);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(6);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/searching1.png"))); // NOI18N

        btn_xemtkb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/schedule.png"))); // NOI18N
        btn_xemtkb.setText("Xem lịch");
        btn_xemtkb.setBorderColor(new java.awt.Color(0, 0, 255));
        btn_xemtkb.setColorClick(new java.awt.Color(102, 102, 255));
        btn_xemtkb.setColorOver(new java.awt.Color(204, 204, 255));
        btn_xemtkb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_xemtkb.setRadius(50);
        btn_xemtkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemtkbActionPerformed(evt);
            }
        });

        btn_nhapdiemsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/floppy-disk.png"))); // NOI18N
        btn_nhapdiemsv.setText("Lưu điểm SV");
        btn_nhapdiemsv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_nhapdiemsv.setRadius(50);
        btn_nhapdiemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_mssv)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_lop)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xemtkb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_lop)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_mssv)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_xemtkb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tra cứu điểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        cb_hocki.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cb_hocki.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        cb_hocki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hockiActionPerformed(evt);
            }
        });

        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Môn học", "Số tín chỉ", "Điểm chuyên cần", "Điểm thi giữa kỳ", "Điểm thi cuối kỳ", "Điểm trung bình", "Xếp loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(2).setHeaderValue("Điểm chuyên cần");
            jTable3.getColumnModel().getColumn(3).setHeaderValue("Điểm thi giữa kỳ");
            jTable3.getColumnModel().getColumn(4).setHeaderValue("Điểm thi cuối kỳ");
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/semester.png"))); // NOI18N
        jLabel2.setText("Chọn học kì");

        cb_nam.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cb_nam.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));
        cb_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_namActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plan.png"))); // NOI18N
        jLabel1.setText("Chọn niên khóa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(cb_hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void DisplayCombobox(){
        //EventcheckText();
        cb_nam.removeAllItems();
        cb_hocki.removeAllItems();
        dem1=0;dem2=0;
        for(int i=1;i<=8;i++)
            cb_hocki.addItem(Integer.toString(i));
        listlhp=new JdbcLopHocPhan();
         if(ms.length()==4)
            listhp=listlhp.select3(ms);
        else
            listhp=listlhp.select2(ms);
        String tam="";
        
        for(LopHocPhan lhp :listhp){
            
            if(!lhp.getNienKhoa().equals(tam)){
                tam=lhp.getNienKhoa();
                System.out.println(tam);
                cb_nam.addItem(tam);    
            } 
        }
        cb_nam.addItem("All");
    }    
    String ms;
    private void EventcheckText(){
        txt_ma.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                warn();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                warn();
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
                warn();
            }

            public void warn() {
                ms=txt_ma.getText();
                // 
            }
        });
    }
    int position;  
    private void cb_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_namActionPerformed
        
        dem1++;                             
        if(dem1>1){
            xemDiem();
            
        }
    
           
    }//GEN-LAST:event_cb_namActionPerformed
    private void xemDiem(){
        listlhp=new JdbcLopHocPhan();
        if(ms.length()==4)
            listhp=listlhp.select3(ms);
        else
            listhp=listlhp.select2(ms);
        DefaultTableModel model=(DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        for(LopHocPhan lhp :listhp){
           // System.out.println(cb_nam.getSelectedItem().toString());
            if(lhp.getHocKy()==Integer.parseInt(cb_hocki.getSelectedItem().toString())&&lhp.getNienKhoa().equals(cb_nam.getSelectedItem().toString())){
                SinhVien_Helper help=new SinhVien_Helper();
                model.addRow(help.DisplayTable2(lhp));
            }
            else if(cb_nam.getSelectedItem().toString().equals("All")){
                SinhVien_Helper help=new SinhVien_Helper();
                model.addRow(help.DisplayTable2(lhp));
            }
        }
        
    }
    
    private void cb_hockiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hockiActionPerformed

        dem2++;
        if(dem2>1){
            xemDiem();
           
        }
    }//GEN-LAST:event_cb_hockiActionPerformed
    
    public LopHocPhan getModel(int row){
        LopHocPhan newLHP=new LopHocPhan();
        newLHP.setMaMH(jTable3.getValueAt(row, 0).toString());
        newLHP.setDiemCC(Float.parseFloat(jTable3.getValueAt(row, 2).toString()));
        newLHP.setDiemThiGK(Float.parseFloat(jTable3.getValueAt(row, 3).toString()));
        newLHP.setDiemThiCK(Float.parseFloat(jTable3.getValueAt(row, 4).toString()));
        //newLHP.setDiemCK(Float.parseFloat(jTable3.getValueAt(row, 5).toString()));
        return newLHP;
    }
    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int row=jTable3.getSelectedRow();
        if(row!=-1){
            try{
                listlhp=new JdbcLopHocPhan();
                LopHocPhan lhpnew=getModel(row);
                if(listlhp.update(lhpnew,ms)>0)
                {
                    JOptionPane.showMessageDialog(this,"update thanh cong");
                    xemDiem();
                }
                else{
                    JOptionPane.showMessageDialog(this,"luu that bai");

                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"loi"+e.toString());

            }
        }
        
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xemtkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemtkbActionPerformed
        if(txt_ma.getText()==null||txt_ma.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text khong duoc de trong", "Canh bao: ", JOptionPane.WARNING_MESSAGE);
        }
        else{
            TKB tkb=new TKB("admin1",txt_ma.getText(),cb_nam.getSelectedItem().toString(),cb_hocki.getSelectedItem().toString());
            tkb.setVisible(true);
            tkb.setLocation(300,200);
            
        }
    }//GEN-LAST:event_btn_xemtkbActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        EventcheckText();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        dem1=1;
        dem2=1;
        position=jTable1.rowAtPoint(evt.getPoint());
        String malhp=jTable1.getValueAt(position, 1).toString();
        DefaultTableModel model=(DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        if(ms.length()==6){
            for(LopHocPhan lhp :listhp){
                if(lhp.getMaLHP().equals(malhp)){
                    SinhVien_Helper help=new SinhVien_Helper();
                    model.addRow(help.DisplayTable2(lhp));
                }
            }
        }
        else{
            LopHocPhan l=new LopHocPhan();
            l=listlhp.xemdiem(malhp, jTable1.getValueAt(position, 0).toString());
            SinhVien_Helper help=new SinhVien_Helper();
            model.addRow(help.DisplayTable2(l));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void rb_mssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mssvActionPerformed
        dem1=0;dem2=0;
        if(txt_ma.getText().equals(null)||txt_ma.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text khong duoc de trong", "Canh bao: ", JOptionPane.WARNING_MESSAGE);
            buttonGroup1.clearSelection();
            return;
        }
        DefaultTableModel modelb=(DefaultTableModel) jTable1.getModel();
        modelb.setRowCount(0);//de reset table
        listsv=new JdbcSinhVien();
        list=listsv.select(txt_ma.getText());
        
        if(!list.isEmpty()){
            for(SinhVien sv :list){
               // JOptionPane.showMessageDialog(this,sv.getMSSV());
                SinhVien_Helper help=new SinhVien_Helper();
                modelb.addRow(help.DisplayTable(sv));

            }
            jTable1.setRowSelectionInterval(0,0);
            DisplayCombobox();
        }
        else{
            JOptionPane.showMessageDialog(null, "Nhap sai ma", "Canh bao: ", JOptionPane.WARNING_MESSAGE);
            buttonGroup1.clearSelection();
            return;
        }
        
    }//GEN-LAST:event_rb_mssvActionPerformed

    private void rb_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_lopActionPerformed
        dem1=0;dem2=0;
        if(txt_ma.getText()==null||txt_ma.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Text khong duoc de trong", "Canh bao: ", JOptionPane.WARNING_MESSAGE);
            buttonGroup1.clearSelection();
            return;
        }
        DefaultTableModel modelb=(DefaultTableModel) jTable1.getModel();
        modelb.setRowCount(0);//de reset table
        listsv=new JdbcSinhVien();
        list=listsv.select1(ms);
        if(!list.isEmpty()){
            for(SinhVien sv :list){
                SinhVien_Helper help=new SinhVien_Helper();
                modelb.addRow(help.DisplayTable(sv));
            }
            jTable1.setRowSelectionInterval(0,0);
            DisplayCombobox();
        }
        else{
            JOptionPane.showMessageDialog(null, "Nhap sai ma", "Canh bao: ", JOptionPane.WARNING_MESSAGE);
            buttonGroup1.clearSelection();
            return;
        }
    }//GEN-LAST:event_rb_lopActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Form.MyButton btn_nhapdiemsv;
    private Form.MyButton btn_xemtkb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_hocki;
    private javax.swing.JComboBox<String> cb_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton rb_lop;
    private javax.swing.JRadioButton rb_mssv;
    private javax.swing.JTextField txt_ma;
    // End of variables declaration//GEN-END:variables
}
