/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Domain.LopHocPhan;
import Domain.SinhVien;
import Repository.GiaoVien_Helper;
import Repository.JdbcGiaoVien;
import Repository.JdbcLopHocPhan;
import Repository.JdbcSinhVien;
import Repository.SinhVien_Helper;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lasin
 */
public class FormGiaoVien extends javax.swing.JFrame {
    JdbcLopHocPhan listlhp;
    DiemSV diemSV;
    /**
     * Creates new form FormGiaoVien
     */
    String ms;
    public FormGiaoVien() {
        initComponents();
    }
    public FormGiaoVien(String tam) 
    {
        ms=tam;
        //JOptionPane.showMessageDialog(null, tam, "Canh bao: ", JOptionPane.WARNING_MESSAGE);
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("/Image/teacher1.png")).getImage();
        this.setIconImage(img);
        SetThongtinGV();
        DisplayCombobox();
    }
     private void SetThongtinGV(){
        JdbcGiaoVien listgv=new JdbcGiaoVien();
        Object otam[]=listgv.thongtingiaovien(ms);
        txt_giaovien.setText(otam[0].toString());
        txt_magv.setText(otam[1].toString());
        txt_makhoa.setText(otam[2].toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_nam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_hocki = new javax.swing.JComboBox<>();
        myButton4 = new Form.MyButton();
        myButton2 = new Form.MyButton();
        btn_nhapdiemsv = new Form.MyButton();
        txt_giaovien = new java.awt.TextField();
        txt_makhoa = new java.awt.TextField();
        txt_magv = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giáo Viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Thông tin giáo viên ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã số giáo viên:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Họ tên giáo viên:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mã Khoa:");

        cb_nam.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cb_nam.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Năm học:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Hoc ki:");

        cb_hocki.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cb_hocki.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancels.png"))); // NOI18N
        myButton4.setText("Đăng Xuất");
        myButton4.setBorderColor(new java.awt.Color(255, 0, 0));
        myButton4.setColorClick(new java.awt.Color(255, 102, 102));
        myButton4.setColorOver(new java.awt.Color(255, 204, 204));
        myButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        myButton4.setRadius(50);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangxuatActionPerformed(evt);
            }
        });

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/schedule.png"))); // NOI18N
        myButton2.setText("Lịch dạy");
        myButton2.setBorderColor(new java.awt.Color(0, 0, 255));
        myButton2.setColorClick(new java.awt.Color(102, 102, 255));
        myButton2.setColorOver(new java.awt.Color(204, 204, 255));
        myButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        myButton2.setRadius(50);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lichActionPerformed(evt);
            }
        });

        btn_nhapdiemsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert.png"))); // NOI18N
        btn_nhapdiemsv.setText("Xem Điểm SV");
        btn_nhapdiemsv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btn_nhapdiemsv.setRadius(50);
        btn_nhapdiemsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemdiemActionPerformed(evt);
            }
        });

        txt_giaovien.setEditable(false);
        txt_giaovien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_makhoa.setEditable(false);
        txt_makhoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txt_magv.setEditable(false);
        txt_magv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(385, 385, 385))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_magv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_giaovien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_makhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel5))
                    .addComponent(txt_giaovien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_makhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(cb_hocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_magv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nhapdiemsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Thông tin giáo viên:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangxuatActionPerformed
        FormDangNhapGV formDangNhapGV =new FormDangNhapGV();
        formDangNhapGV.setVisible(true);
        this.setVisible(false);
        formDangNhapGV.setLocation(400,400);
    }//GEN-LAST:event_btn_dangxuatActionPerformed

    private void btn_lichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lichActionPerformed
        TKB tkb=new TKB("giaovien",txt_magv.getText(),cb_nam.getSelectedItem().toString(),cb_hocki.getSelectedItem().toString());
        tkb.setVisible(true);
        tkb.setLocation(400,100);
    }//GEN-LAST:event_btn_lichActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        FormDangNhapGV formDangNhapGV =new FormDangNhapGV();
        formDangNhapGV.setVisible(true);
        formDangNhapGV.setLocation(400,400);
    }//GEN-LAST:event_formWindowClosing

    private void btn_xemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemdiemActionPerformed
        diemSV=new DiemSV("giaovien");
        diemSV.setVisible(true);
        diemSV.setLocation(400,400);
    }//GEN-LAST:event_btn_xemdiemActionPerformed

    private void DisplayCombobox(){
        cb_nam.removeAllItems();
        cb_hocki.removeAllItems();
        for(int i=1;i<=8;i++)
            cb_hocki.addItem(Integer.toString(i));
        listlhp=new JdbcLopHocPhan();
        List<String>lhp=new ArrayList<>();
        lhp=listlhp.getNienKhoa();
        for(String tam :lhp){
            cb_nam.addItem(tam);                
        } 
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Form.MyButton btn_nhapdiemsv;
    private javax.swing.JComboBox<String> cb_hocki;
    private javax.swing.JComboBox<String> cb_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private Form.MyButton myButton2;
    private Form.MyButton myButton4;
    private java.awt.TextField txt_giaovien;
    private java.awt.TextField txt_magv;
    private java.awt.TextField txt_makhoa;
    // End of variables declaration//GEN-END:variables
}
